port: 80
url: http://www.hanting.tech
filter: 'category'
recent_num: 20
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
	sass_dir: _sass
        style: compressed


plugins:
  - jekyll-seo-tag
  - jekyll-feed        

